# Generated by Django 4.2 on 2023-04-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
