# Generated by Django 4.1.7 on 2023-07-04 09:12

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_full_form_community_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to=base.models.Community.get_image_path),
        ),
    ]
