# Generated by Django 4.1.7 on 2023-06-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='roll_no',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodreq',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='BloodDonatedStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('roll_no', models.CharField(max_length=8, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bloodreq')),
            ],
        ),
    ]
