# Generated by Django 4.1.7 on 2023-06-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_blooddonatedstudents_blood_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodreq',
            name='contact',
        ),
    ]
