# Generated by Django 4.1.7 on 2023-06-17 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_blooddonatedstudents_id_alter_blooddonation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonatedstudents',
            name='donated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
