# Generated by Django 4.1.7 on 2023-06-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_blooddonatedstudents_donated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonatedstudents',
            name='donated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
