# Generated by Django 4.1.7 on 2023-06-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_blooddonatedstudents_donated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
