# Generated by Django 4.1.7 on 2023-07-01 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_fests_description_fests_full_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('full_form', models.TextField(blank=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='carousel',
            name='news',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='base.news'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='program',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='base.program'),
        ),
    ]
