# Generated by Django 4.1.7 on 2023-07-01 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_community_carousel_news_carousel_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='news',
            field=models.ForeignKey(blank=True, default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='base.news'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='program',
            field=models.ForeignKey(blank=True, default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='base.program'),
        ),
    ]
