# Generated by Django 4.1.7 on 2023-07-01 12:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_carousel_news_alter_carousel_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='community',
            field=models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.community'),
        ),
        migrations.AddField(
            model_name='news',
            name='fest',
            field=models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.fests'),
        ),
        migrations.AddField(
            model_name='program',
            name='community',
            field=models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.community'),
        ),
        migrations.AddField(
            model_name='program',
            name='fest',
            field=models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.fests'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='news',
            field=models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.news'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='program',
            field=models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.program'),
        ),
    ]
