# Generated by Django 4.1.7 on 2023-07-03 12:44

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_course_exploreimg_blooddonation_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_by',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to=base.models.Carousel.get_image_path),
        ),
        migrations.AlterField(
            model_name='explore',
            name='image',
            field=models.ImageField(upload_to=base.models.Explore.get_image_path),
        ),
        migrations.AlterField(
            model_name='exploreimg',
            name='image',
            field=models.ImageField(upload_to=base.models.Exploreimg.get_image_path),
        ),
        migrations.AlterField(
            model_name='fests',
            name='logo',
            field=models.ImageField(default='default_image.jpg', upload_to=base.models.Fests.get_image_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to=base.models.News.get_image_path),
        ),
    ]
