# Generated by Django 4.1.7 on 2023-07-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_news_created_by_alter_carousel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='community',
        ),
        migrations.RemoveField(
            model_name='news',
            name='fest',
        ),
        migrations.RemoveField(
            model_name='program',
            name='community',
        ),
        migrations.RemoveField(
            model_name='program',
            name='fest',
        ),
    ]
