# Generated by Django 4.1.7 on 2023-07-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_news_community_remove_news_fest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='created_by',
            field=models.TextField(blank=True),
        ),
    ]
