# Generated by Django 4.1.7 on 2023-07-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_program_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='created_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
